In [1]:
%config IPCompleter.greedy=True
%matplotlib inline

In [2]:
import pandas as pd, numpy as np, os, sys
import matplotlib
import matplotlib.pyplot as plt
from matplotlib.ticker import FuncFormatter
from IPython.display import display, HTML
from IPython.core.debugger import Tracer
from IPython.core.debugger import Pdb

font = {'size'   : 18}
matplotlib.rc('font', **font)

def plotHorizontalBars(series, xlabel, title):
    xpos = np.arange(len(series.index), 0, -1)
    plt.barh(xpos, series, align='center', alpha=0.5, color='g')
    plt.grid(axis='x')
    plt.yticks(xpos, series.index)
    plt.xlabel(xlabel)
    plt.title(title)

def plotVerticalBars(series, ylabel, title):
    xpos = np.arange(len(series.index), 0, -1)
    plt.bar(xpos, series, align='center', alpha=0.5, color='g')
    plt.grid(axis='y')
    plt.xticks(xpos, series.index)
    plt.ylabel(ylabel)
    plt.title(title)

In [5]:
samples = 80000
n_vals = 5
yv = [chr(ord('a')+i) for i in range(n_vals)]

x = range(samples)
y = np.array(yv * (samples // n_vals)); np.random.shuffle(y)
a = pd.DataFrame(np.column_stack((x, y)), columns=['x', 'y'])
a.x = a.x.astype('int64')
display(a.head(10))
print(a.shape)

x  y
0  0  e
1  1  b
2  2  c
3  3  e
4  4  b
5  5  b
6  6  e
7  7  c
8  8  e
9  9  c

(80000, 2)


In [9]:
from sklearn.feature_extraction import DictVectorizer
from sklearn.feature_extraction.text import CountVectorizer

vec = DictVectorizer(sparse=False, dtype=int)
samples = ['feature selection', 'feature engineering', 'feature extraction']
vec = CountVectorizer()
X = vec.fit_transform(samples)
print(X)
print(X.toarray())
print(vec.get_feature_names())

  (0, 3)	1
  (0, 2)	1
  (1, 0)	1
  (1, 2)	1
  (2, 1)	1
  (2, 2)	1
[[0 0 1 1]
 [1 0 1 0]
 [0 1 1 0]]
['engineering', 'extraction', 'feature', 'selection']


In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer
vec= TfidfVectorizer()
X = vec.fit_transform(samples)
print(X.toarray())

[[0.         0.         0.50854232 0.861037  ]
 [0.861037   0.         0.50854232 0.        ]
 [0.         0.861037   0.50854232 0.        ]]
